### ISSUE TITLE
Visualization of chimeric transcript from Non-human organism

### ISSUE THREAD

**Issue by wyzhangMPI** [stianlagstad/chimeraviz#14]
Hi,
   I would like to know whether chimeraviz can be used for the visualization of the chimeric transcript from non-human organims. I tried import the fusion data with "fusions <- importStarfusion(defuse833ke, "mm10")", but failed with genome version info.

Thanks!

Best,
Wenyu Zhang

**Comment by stianlagstad** [comment]
Hi,

Thank you for your interest in chimeraviz! Currently the package only supports the human genome (hg19 and hg38), but it would be interesting to improve chimeraviz to support other genomes as well. Is it only the mm10 genome you're interested in?

Note to self:
- mm10 cytoband data can be found here: http://hgdownload.cse.ucsc.edu/goldenpath/mm10/database/
- edb can be created with gtf file from here: ftp://ftp.ensembl.org/pub/release-74/gtf/mus_musculus/
- Also look at http://www.sanger.ac.uk/science/data/mouse-genomes-project

**Comment by wyzhangMPI** [comment]
Yes, mm10 is my current interest. Would that be possible that to guide the chimeraviz to read in the mm10 meta data, i.e., cytoband data, and do the visualization?
Thanks!

**Comment by stianlagstad** [comment]
Are you able to share your fusion finder results file, as well as a corresponding .bam file? That would help me add support for mm10 much faster :)

**Comment by wyzhangMPI** [comment]
Hi,
I will upload the dataset to our ftp server tomorrow and provide you the link then.
Thanks!


Best,
Wenyu


Original Message
Sender:Stian Lågstadnotifications@github.com
Recipient:stianlagstad/chimeravizchimeraviz@noreply.github.com
Cc:wyzhangMPIwyzhang@evolbio.mpg.de; Authorauthor@noreply.github.com
Date:Tuesday, Nov 28, 2017 18:29
Subject:Re: [stianlagstad/chimeraviz] Visualization of chimeric transcriptfrom Non-human organism (#14)


Are you able to share your fusion finder results file, as well as the corresponding .bam file? That would help me add support for mm10 much faster :)

**Comment by stianlagstad** [comment]
Great! If there are no unexpected problems then it won't take long for me to implement support for mm10 :)

**Comment by wyzhangMPI** [comment]
Hi,
     I upload all the data from the output of star-fusion: 
http://web.evolbio.mpg.de/~wyzhang/Webdav_Pub/star_fusion_outdir/. You 
can find the tsv and bam file there.
     Look forward to seeing that chimeraviz works on mm10.
     Thanks!

Best,
Wenyu


Dr Wenyu Zhang
Department of Evolutionary Genetics,
Max Planck Institute for Evolutionary Biology
August-Thienemann-str 2
24306 Plön (Germany)
E-mail address: wyzhang@evolbio.mpg.de
Phone number: +49 4522 763 372 (Office)


------ Original Message ------

**Comment by stianlagstad** [comment]
If you can install chimeraviz from git now (with `devtools::install_git("https://git.bioconductor.org/packages/chimeraviz.git")`), mm10 should work :) I've done some testing, but there might a couple of bugs I've missed. Please let me know about any issues you run into.

Note that this is the development version of chimeraviz. You might have to use a newer version of R, and newer versions of the supporting Bioconductor packages.

**Comment by wyzhangMPI** [comment]
Hi,
   I tried with newest R version, and it seems that works well. I will let you know if any further issues.
   Thanks so much!

**Comment by stianlagstad** [comment]
I'm sorry about that - it might've been because `devtools::install_git` didn't install all the dependencies. The development version of chimeraviz (available at https://bioconductor.org/packages/devel/bioc/html/chimeraviz.html) has been updated to reflect yesterdays changes. So if you're able to install it from the instructions there, you should be good to go. Note however that the development version of Bioconductor is having some issues with CRAN packages on Windows at the moment, so it might not work for you if you're using Windows.

However, if you're able to work with Docker, I just tested it and that works. Dockerfile:
```
FROM bioconductor/devel_core2

RUN R -e 'source("https://bioconductor.org/biocLite.R");biocLite("chimeraviz")'
```
Build that with `docker build . -t chimeravizDevBuild` (will take a few minutes). Then start with `docker run -it -p 8787:8787 chimeravizDevBuild`. http://localhost:8787/ should then work:
![screenshot from 2017-12-01 15-10-43](https://user-images.githubusercontent.com/4340859/33486312-d786d0b2-d6a9-11e7-9e99-94de2df176db.png)

The [Bioconductor Docker images](https://www.bioconductor.org/help/docker/) are built from [the rocker:rstudio images](https://hub.docker.com/r/rocker/rstudio/), which give you the very nice Rstudio server.

**Comment by wyzhangMPI** [comment]
Hi,
     Sorry, I just updated my comments.
     I manually downloaded org.Mm.eg.db through bioconductor, and now it 
works well.
     Thanks!

Best,
Wenyu


------ Original Message ------

**Comment by stianlagstad** [comment]
That's great :) Do let me know how the mm10 support works for you. Just reopen this issue if there are any problems.
