### ISSUE TITLE
What do the link widths represent in the overview plot? 

### ISSUE THREAD

**Issue by komalsrathi** [stianlagstad/chimeraviz#41]
Hi Stian,

I was trying to create the overview plot but a little confused as to what the link widths mean here:

https://bioconductor.org/packages/release/bioc/vignettes/chimeraviz/inst/doc/chimeraviz-vignette.html#building-the-overview-plot

Initially I thought it represents how many times the event was observed. But the width between `EDA-RFWD3` is greater than `EEF1A1P5-PABPC1` even though `EEF1A1P5-PABPC1` is seen 4 times and `EDA-RFWD3` is seen only once. Can you please explain? 

Thank you,
Komal

**Comment by stianlagstad** [comment]
Hey @komalsrathi! The link width just signifies how many supporting reads (spanning + split) support that fusion event. But it's scaled compared to the other fusion events in the list. So that if you have this list of fusion events:
- fusion1 with 5 supporting reads
- fusion2 with 10 supporting reads
- fusion3 with 42 supporting reads

then the width of fusion3 would be the biggest. Does that make sense?

**Comment by komalsrathi** [comment]
Oh alright - I have been misunderstanding it as the number of times/samples it was seen in. Thanks for clarifying!
