### ISSUE TITLE
Dependency on deprecated ArgumentCheck CRAN package

### ISSUE THREAD

**Issue by mattheiter** [stianlagstad/chimeraviz#93]
ArgumentCheck has been deprecated, which means that chimeraviz cannot be installed using BiocManager anymore:

https://cran.rstudio.com/web/packages/ArgumentCheck/index.html

Migration instructions are available here: https://github.com/cran/ArgumentCheck

**Comment by stianlagstad** [comment]
Thanks for the notification, @matdoering ! The author of ArgumentCheck was kind enough to [notify me about this here](https://github.com/stianlagstad/chimeraviz/pull/90), and I changed chimeraviz to use another package as a replacement [here](https://github.com/stianlagstad/chimeraviz/pull/91). Version 1.17.2 of chimeraviz (and newer) is using checkmate instead of argumentcheck.

Which version of chimeraviz did you attempt to install?
